### ISSUE TITLE
Windows 11 cmd not work.

### ISSUE THREAD

**Issue by salan668** [schorschinho/LCModel#3]
Hi, Thanks for providing the complied exe file for windows. 

However, when run the test cmd "lcmodel < control.file", the character "<" can not be used in windows cmd. 

If I run the comannd ".\lcmodel control.file" nothing will happen.

Is there any mistakes here i made?

Thank you.

![image](https://github.com/user-attachments/assets/96da941f-2e32-49e0-93d4-628679669ce1)

Windows11, 64bit

**Comment by schorschinho** [comment]
This seems to be a problem with PowerShell not supporting the < redirection. Can you try in the regular terminal (Start - Run - cmd.exe) instead?

**Comment by salan668** [comment]
@schorschinho Thanks for your quick response. 

it works!
